#..this tests the R engine's ability to interface with/install package dependencies 
#  While it's not super important that we be able to dynamically install packages, 
#  on the fly it's essential that we be able to call them from within the engine 
install.packages('dplyr')
require(dplyr)

#..some very dumb functions intended to test the ability to source R script files
#  into the global env of the R engine generated by R.NET  
mean_function <- function(x) mean(x, na.rm = TRUE)
median_function <- function(x) median(x, na.rm = TRUE)
